# Знакомство с *numpy*

In [102]:
import numpy as np
from numpy import doc

help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    /Users/aleksan/Code/python_learn/venv/lib/python3.9/site-packages/numpy/doc/__init__.py




In [103]:
np.array

<function numpy.array>

In [104]:
a = np.array([1, 2, 3])
print(repr(a))
print(type(a))

array([1, 2, 3])
<class 'numpy.ndarray'>


In [105]:
print(a.ndim)
print(a.shape)

1
(3,)


In [106]:
a.dtype

dtype('int64')

In [107]:
a.itemsize

8

In [108]:
b = np.array([[4, 5, 6], [7, 8, 9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [109]:
print(b.size)
print(b.ndim)
print(b.shape)

6
2
(2, 3)


In [111]:
print(repr(b.dtype))
print(b.dtype.name)
b.dtype = np.int32
print(b.dtype)
print(b.itemsize)

dtype('int32')
int32
int32
4


In [112]:
a = np.arange(15)
print(a)
a = a.reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [113]:
b = np.arange(15, 115, 5).reshape(4, 5)
print(b)

[[ 15  20  25  30  35]
 [ 40  45  50  55  60]
 [ 65  70  75  80  85]
 [ 90  95 100 105 110]]


In [114]:
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(4, 5)
2
20
int64


In [115]:
a = np.arange(1, 5, 0.5)
print(a)
print(a.size)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
8


In [116]:
a = np.arange(0, 2, 0.3)
print(a)
print(a.size)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
7


In [117]:
a = np.linspace(0, 6, 20)
a

array([0.        , 0.31578947, 0.63157895, 0.94736842, 1.26315789,
       1.57894737, 1.89473684, 2.21052632, 2.52631579, 2.84210526,
       3.15789474, 3.47368421, 3.78947368, 4.10526316, 4.42105263,
       4.73684211, 5.05263158, 5.36842105, 5.68421053, 6.        ])

In [118]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [119]:
SIZE = 10
SHAPE = (SIZE, )

res = np.zeros(SHAPE)
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
res.dtype

dtype('float64')

In [121]:
res = np.zeros(SHAPE, dtype=a.dtype)
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [122]:
print(res.dtype)

int64


In [126]:
for i in range(SIZE):
    res[i] = a[i] + b[i]

res

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [127]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [128]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [129]:
SHAPE = 2, 3
a = np.arange(1, 7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [130]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [131]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [132]:
a = np.arange(7)
b = np.arange(9)

# expected exception
# a + b

In [133]:
np.arange(10, 20) / np.arange(10)

<ipython-input-133-22415263f89d>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.arange(10, 20) / np.arange(10)


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

In [134]:
a = np.arange(10)
print(a)
np.diff(a)

[0 1 2 3 4 5 6 7 8 9]


array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [135]:
a = np.arange(10, 50, 5).reshape(2, 4)
print(a)
np.diff(a)

[[10 15 20 25]
 [30 35 40 45]]


array([[5, 5, 5],
       [5, 5, 5]])

In [136]:
a * 3

array([[ 30,  45,  60,  75],
       [ 90, 105, 120, 135]])

In [137]:
np.diff(a * 4)

array([[20, 20, 20],
       [20, 20, 20]])

In [138]:
np.sum(a)

220

In [139]:
np.sum(a * 3)

660

In [140]:
a.ndim

2

In [141]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [142]:
np.sum(a, axis=0)

array([40, 50, 60, 70])

In [143]:
np.sum(a, axis=1)

array([ 70, 150])

In [144]:
np.prod(a)

141750000000

In [145]:
np.prod(a, axis=0)

array([ 300,  525,  800, 1125])

In [146]:
np.prod(a, axis=1)

array([  75000, 1890000])

In [147]:
a ** 2

array([[ 100,  225,  400,  625],
       [ 900, 1225, 1600, 2025]])

In [148]:
np.sqrt(a)

array([[3.16227766, 3.87298335, 4.47213595, 5.        ],
       [5.47722558, 5.91607978, 6.32455532, 6.70820393]])

In [149]:
a > 30

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [150]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [151]:
b = np.linspace(40, 75, 8, dtype=np.int64).reshape(2, 4)
b

array([[40, 45, 50, 55],
       [60, 65, 70, 75]])

In [152]:
a < b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [153]:
b = np.arange(50, 10, -5).reshape(2, 4)
b

array([[50, 45, 40, 35],
       [30, 25, 20, 15]])

In [154]:
a > b

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [155]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [156]:
a.dtype

dtype('int64')

In [157]:
a / 3

array([[ 3.33333333,  5.        ,  6.66666667,  8.33333333],
       [10.        , 11.66666667, 13.33333333, 15.        ]])

In [158]:
(a / 3) >= b

array([[False, False, False, False],
       [False, False, False,  True]])

In [159]:
a // 3

array([[ 3,  5,  6,  8],
       [10, 11, 13, 15]])

In [160]:
a // b

array([[0, 0, 0, 0],
       [1, 1, 2, 3]])

In [161]:
a % b

array([[10, 15, 20, 25],
       [ 0, 10,  0,  0]])

In [162]:
print(a)
print(b)

[[10 15 20 25]
 [30 35 40 45]]
[[50 45 40 35]
 [30 25 20 15]]


In [163]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [164]:
a[8]

512

In [165]:
a[2:5]

array([ 8, 27, 64])

In [166]:
a[:4]

array([ 0,  1,  8, 27])

In [167]:
a[7:]

array([343, 512, 729])

In [168]:
a[3:9:2]

array([ 27, 125, 343])

In [169]:
a[3::2]

array([ 27, 125, 343, 729])

In [170]:
a[::3]

array([  0,  27, 216, 729])

In [171]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [172]:
a[:9:3]

array([  0,  27, 216])

In [173]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [174]:
a[:9:3] = 123
a

array([123,   1,   8, 123,  64, 125, 123, 343, 512, 729])

In [175]:
SHAPE = 5, 4

b = np.arange(20).reshape(SHAPE)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [176]:
def f(x, y):
    print(x)
    print(y)
    return 10 * x + y

print(f(3, 4))

3
4
34


In [177]:
np.fromfunction(f, SHAPE)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [178]:
def inc_by_index_1(x):
    # 0, 1, 2, 3, 4
    # 0, 1, 3, 6, 10
    # print(x)
    if not (x > 0):
        return x
    return x + inc_by_index_1(x - 1)

print(inc_by_index_1(1))
print(inc_by_index_1(2))
print(inc_by_index_1(3))

1
3
6


In [179]:
a = np.arange(20, 60, 2).reshape(5, 4)
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [180]:
a[1]

array([28, 30, 32, 34])

In [181]:
a[3]

array([44, 46, 48, 50])

In [182]:
a[4][0]

52

In [183]:
a[4, 0]

52

In [184]:
a[:, 3]

array([26, 34, 42, 50, 58])

In [185]:
a[1:3, :2]

array([[28, 30],
       [36, 38]])

In [186]:
a[-1]

array([52, 54, 56, 58])

In [187]:
a[::-1]

array([[52, 54, 56, 58],
       [44, 46, 48, 50],
       [36, 38, 40, 42],
       [28, 30, 32, 34],
       [20, 22, 24, 26]])

In [188]:
a[::-1, ::-1]

array([[58, 56, 54, 52],
       [50, 48, 46, 44],
       [42, 40, 38, 36],
       [34, 32, 30, 28],
       [26, 24, 22, 20]])

In [189]:
a.transpose()

array([[20, 28, 36, 44, 52],
       [22, 30, 38, 46, 54],
       [24, 32, 40, 48, 56],
       [26, 34, 42, 50, 58]])

In [190]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [191]:
a_t = a.transpose()
a_t

array([[20, 28, 36, 44, 52],
       [22, 30, 38, 46, 54],
       [24, 32, 40, 48, 56],
       [26, 34, 42, 50, 58]])

In [192]:
print(a[0])
print(a_t[0])

[20 22 24 26]
[20 28 36 44 52]


In [193]:
print(a[:, 0])

[20 28 36 44 52]


In [211]:
SHAPE_3D = (2, 4, 6)

a = np.arange(48).reshape(SHAPE_3D)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [212]:
print(a.ndim)
print(a.size)
print(a.shape)

3
48
(2, 4, 6)


In [213]:
print(a[1])
print(a[:, 3])
print(a[:, :, 5])

[[24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
[[18 19 20 21 22 23]
 [42 43 44 45 46 47]]
[[ 5 11 17 23]
 [29 35 41 47]]


In [214]:
a[1, 3, 5]

47

In [215]:
a[..., 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [216]:
a ** 5

array([[[        0,         1,        32,       243,      1024,
              3125],
        [     7776,     16807,     32768,     59049,    100000,
            161051],
        [   248832,    371293,    537824,    759375,   1048576,
           1419857],
        [  1889568,   2476099,   3200000,   4084101,   5153632,
           6436343]],

       [[  7962624,   9765625,  11881376,  14348907,  17210368,
          20511149],
        [ 24300000,  28629151,  33554432,  39135393,  45435424,
          52521875],
        [ 60466176,  69343957,  79235168,  90224199, 102400000,
         115856201],
        [130691232, 147008443, 164916224, 184528125, 205962976,
         229345007]]])

In [217]:
SHAPE_5D = tuple(range(2, 7))
SHAPE_5D

(2, 3, 4, 5, 6)

In [218]:
d = np.empty(SHAPE_5D, dtype=np.int16)
d

array([[[[[     0,      0,      0,      0,    230,      0],
          [     0,      0,      0,      0,      0,      0],
          [ 19430,   2318,      1,      0,      0,      0],
          [     0,      0,      0,      0,      0,      0],
          [    -1,     -1,     -1,     -1,      0,      0]],

         [[     0,      0,      1,      0,      1,      0],
          [     0,      0,      0,      0,      9,      0],
          [     0,      0,  30561,  13131,      1,      0],
          [ 14684,  -8827,  32706,      0,     -1,     -1],
          [    -1,     -1,      0,      0,      0,      0]],

         [[    -1,     -1,     -1,     -1,      0,      0],
          [     0,      0,      1,      0,      1,      0],
          [    72,      0,      0,      0,     11,      0],
          [     0,      0,  30561,  13131,      1,      0],
          [ 14700,  -8827,  32706,      0,      1,      0]],

         [[     0,      0,     28,      0,      0,      0],
          [    -1,     -1,     -1,

In [219]:
d[1, :, :, :, 5]

array([[[ 2129,     0,  2128,     0,  2140],
        [    0,  2157,     0,  2128,     0],
        [ 2136,     0,  2140,     0,  2157],
        [    0,  2133,     0,  2132,     0]],

       [[ 2131,     0,  2127,     0,  2128],
        [    0,  2137,     0,  2156,  8224],
        [ 8240,  8224,  8224,  8224,  8241],
        [13877,  8224,  8224,  8246,  8224]],

       [[ 8224,  8224,  8241, 12595,  2570],
        [ 8241, 12595,  8224,  2653,  8240],
        [ 8224, 13613,  2653,  8241, 12857],
        [ 8224,  2653,  8248,  8224, 14637]]], dtype=int16)

In [220]:
d[1, ..., 5]

array([[[ 2129,     0,  2128,     0,  2140],
        [    0,  2157,     0,  2128,     0],
        [ 2136,     0,  2140,     0,  2157],
        [    0,  2133,     0,  2132,     0]],

       [[ 2131,     0,  2127,     0,  2128],
        [    0,  2137,     0,  2156,  8224],
        [ 8240,  8224,  8224,  8224,  8241],
        [13877,  8224,  8224,  8246,  8224]],

       [[ 8224,  8224,  8241, 12595,  2570],
        [ 8241, 12595,  8224,  2653,  8240],
        [ 8224, 13613,  2653,  8241, 12857],
        [ 8224,  2653,  8248,  8224, 14637]]], dtype=int16)

In [221]:
print(d.shape)
print((d[1, ..., 5]).shape)

(2, 3, 4, 5, 6)
(3, 4, 5)


In [222]:
d[..., 4, 5]

array([[[    0,     0,     0,     0],
        [    0,     0,     0,     0],
        [ 2131,     0,  2131,     0]],

       [[ 2140,     0,  2157,     0],
        [ 2128,  8224,  8241,  8224],
        [ 2570,  8240, 12857, 14637]]], dtype=int16)

In [224]:
from numpy import linalg


a = np.arange(18).reshape((2,3,3))
print(a)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [225]:
print(linalg.det(a))

[0. 0.]
